// Code generated by ent, DO NOT EDIT.

package openaioauthsyncsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldAccountID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldSessionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLTE(FieldAccountID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.FieldContainsFold(FieldSessionID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIOAuthSyncSession) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIOAuthSyncSession) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIOAuthSyncSession) predicate.OpenAIOAuthSyncSession {
	return predicate.OpenAIOAuthSyncSession(sql.NotPredicates(p))
}
