// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionpool"
)

// OpenAIOAuthDailySessionPool is the model entity for the OpenAIOAuthDailySessionPool schema.
type OpenAIOAuthDailySessionPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// BusinessDate holds the value of the "business_date" field.
	BusinessDate string `json:"business_date,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation string `json:"generation,omitempty"`
	// StreamSession0 holds the value of the "stream_session_0" field.
	StreamSession0 string `json:"stream_session_0,omitempty"`
	// StreamSession1 holds the value of the "stream_session_1" field.
	StreamSession1 string `json:"stream_session_1,omitempty"`
	// StreamSession2 holds the value of the "stream_session_2" field.
	StreamSession2 string `json:"stream_session_2,omitempty"`
	// SyncSession holds the value of the "sync_session" field.
	SyncSession string `json:"sync_session,omitempty"`
	// ActiveStreams holds the value of the "active_streams" field.
	ActiveStreams int `json:"active_streams,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIOAuthDailySessionPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaioauthdailysessionpool.FieldID, openaioauthdailysessionpool.FieldAccountID, openaioauthdailysessionpool.FieldActiveStreams:
			values[i] = new(sql.NullInt64)
		case openaioauthdailysessionpool.FieldBusinessDate, openaioauthdailysessionpool.FieldGeneration, openaioauthdailysessionpool.FieldStreamSession0, openaioauthdailysessionpool.FieldStreamSession1, openaioauthdailysessionpool.FieldStreamSession2, openaioauthdailysessionpool.FieldSyncSession:
			values[i] = new(sql.NullString)
		case openaioauthdailysessionpool.FieldCreatedAt, openaioauthdailysessionpool.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIOAuthDailySessionPool fields.
func (_m *OpenAIOAuthDailySessionPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaioauthdailysessionpool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaioauthdailysessionpool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaioauthdailysessionpool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaioauthdailysessionpool.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaioauthdailysessionpool.FieldBusinessDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_date", values[i])
			} else if value.Valid {
				_m.BusinessDate = value.String
			}
		case openaioauthdailysessionpool.FieldGeneration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.String
			}
		case openaioauthdailysessionpool.FieldStreamSession0:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_session_0", values[i])
			} else if value.Valid {
				_m.StreamSession0 = value.String
			}
		case openaioauthdailysessionpool.FieldStreamSession1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_session_1", values[i])
			} else if value.Valid {
				_m.StreamSession1 = value.String
			}
		case openaioauthdailysessionpool.FieldStreamSession2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_session_2", values[i])
			} else if value.Valid {
				_m.StreamSession2 = value.String
			}
		case openaioauthdailysessionpool.FieldSyncSession:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_session", values[i])
			} else if value.Valid {
				_m.SyncSession = value.String
			}
		case openaioauthdailysessionpool.FieldActiveStreams:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_streams", values[i])
			} else if value.Valid {
				_m.ActiveStreams = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIOAuthDailySessionPool.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIOAuthDailySessionPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIOAuthDailySessionPool.
// Note that you need to call OpenAIOAuthDailySessionPool.Unwrap() before calling this method if this OpenAIOAuthDailySessionPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIOAuthDailySessionPool) Update() *OpenAIOAuthDailySessionPoolUpdateOne {
	return NewOpenAIOAuthDailySessionPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIOAuthDailySessionPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIOAuthDailySessionPool) Unwrap() *OpenAIOAuthDailySessionPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIOAuthDailySessionPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIOAuthDailySessionPool) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIOAuthDailySessionPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("business_date=")
	builder.WriteString(_m.BusinessDate)
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(_m.Generation)
	builder.WriteString(", ")
	builder.WriteString("stream_session_0=")
	builder.WriteString(_m.StreamSession0)
	builder.WriteString(", ")
	builder.WriteString("stream_session_1=")
	builder.WriteString(_m.StreamSession1)
	builder.WriteString(", ")
	builder.WriteString("stream_session_2=")
	builder.WriteString(_m.StreamSession2)
	builder.WriteString(", ")
	builder.WriteString("sync_session=")
	builder.WriteString(_m.SyncSession)
	builder.WriteString(", ")
	builder.WriteString("active_streams=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActiveStreams))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIOAuthDailySessionPools is a parsable slice of OpenAIOAuthDailySessionPool.
type OpenAIOAuthDailySessionPools []*OpenAIOAuthDailySessionPool
