// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthsyncsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIOAuthSyncSessionDelete is the builder for deleting a OpenAIOAuthSyncSession entity.
type OpenAIOAuthSyncSessionDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthSyncSessionMutation
}

// Where appends a list predicates to the OpenAIOAuthSyncSessionDelete builder.
func (_d *OpenAIOAuthSyncSessionDelete) Where(ps ...predicate.OpenAIOAuthSyncSession) *OpenAIOAuthSyncSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIOAuthSyncSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthSyncSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIOAuthSyncSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaioauthsyncsession.Table, sqlgraph.NewFieldSpec(openaioauthsyncsession.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIOAuthSyncSessionDeleteOne is the builder for deleting a single OpenAIOAuthSyncSession entity.
type OpenAIOAuthSyncSessionDeleteOne struct {
	_d *OpenAIOAuthSyncSessionDelete
}

// Where appends a list predicates to the OpenAIOAuthSyncSessionDelete builder.
func (_d *OpenAIOAuthSyncSessionDeleteOne) Where(ps ...predicate.OpenAIOAuthSyncSession) *OpenAIOAuthSyncSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIOAuthSyncSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaioauthsyncsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthSyncSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
