// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionaffinity"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIOAuthDailySessionAffinityUpdate is the builder for updating OpenAIOAuthDailySessionAffinity entities.
type OpenAIOAuthDailySessionAffinityUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthDailySessionAffinityMutation
}

// Where appends a list predicates to the OpenAIOAuthDailySessionAffinityUpdate builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) Where(ps ...predicate.OpenAIOAuthDailySessionAffinity) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableAccountID(v *int64) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) AddAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableAPIKeyID(v *int64) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) AddAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetLogicalSessionKey(v)
	return _u
}

// SetNillableLogicalSessionKey sets the "logical_session_key" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableLogicalSessionKey(v *string) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetLogicalSessionKey(*v)
	}
	return _u
}

// SetBusinessDate sets the "business_date" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetBusinessDate(v)
	return _u
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableBusinessDate(v *string) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetBusinessDate(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableGeneration(v *string) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetSlotIndex sets the "slot_index" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.ResetSlotIndex()
	_u.mutation.SetSlotIndex(v)
	return _u
}

// SetNillableSlotIndex sets the "slot_index" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableSlotIndex(v *int) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetSlotIndex(*v)
	}
	return _u
}

// AddSlotIndex adds value to the "slot_index" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) AddSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.AddSlotIndex(v)
	return _u
}

// SetStreamSessionID sets the "stream_session_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetStreamSessionID(v)
	return _u
}

// SetNillableStreamSessionID sets the "stream_session_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableStreamSessionID(v *string) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetStreamSessionID(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetActive(v bool) *OpenAIOAuthDailySessionAffinityUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SetNillableActive(v *bool) *OpenAIOAuthDailySessionAffinityUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the OpenAIOAuthDailySessionAffinityMutation object of the builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) Mutation() *OpenAIOAuthDailySessionAffinityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionaffinity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := openaioauthdailysessionaffinity.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdate) check() error {
	if v, ok := _u.mutation.LogicalSessionKey(); ok {
		if err := openaioauthdailysessionaffinity.LogicalSessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_session_key", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.logical_session_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionaffinity.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.business_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := openaioauthdailysessionaffinity.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSessionID(); ok {
		if err := openaioauthdailysessionaffinity.StreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.stream_session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthDailySessionAffinityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthdailysessionaffinity.Table, openaioauthdailysessionaffinity.Columns, sqlgraph.NewFieldSpec(openaioauthdailysessionaffinity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LogicalSessionKey(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLogicalSessionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.SlotIndex(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotIndex(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StreamSessionID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldStreamSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthdailysessionaffinity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIOAuthDailySessionAffinityUpdateOne is the builder for updating a single OpenAIOAuthDailySessionAffinity entity.
type OpenAIOAuthDailySessionAffinityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIOAuthDailySessionAffinityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableAccountID(v *int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) AddAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableAPIKeyID(v *int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) AddAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetLogicalSessionKey(v)
	return _u
}

// SetNillableLogicalSessionKey sets the "logical_session_key" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableLogicalSessionKey(v *string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetLogicalSessionKey(*v)
	}
	return _u
}

// SetBusinessDate sets the "business_date" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetBusinessDate(v)
	return _u
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableBusinessDate(v *string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetBusinessDate(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableGeneration(v *string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetSlotIndex sets the "slot_index" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.ResetSlotIndex()
	_u.mutation.SetSlotIndex(v)
	return _u
}

// SetNillableSlotIndex sets the "slot_index" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableSlotIndex(v *int) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetSlotIndex(*v)
	}
	return _u
}

// AddSlotIndex adds value to the "slot_index" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) AddSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.AddSlotIndex(v)
	return _u
}

// SetStreamSessionID sets the "stream_session_id" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetStreamSessionID(v)
	return _u
}

// SetNillableStreamSessionID sets the "stream_session_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableStreamSessionID(v *string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetStreamSessionID(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetActive(v bool) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SetNillableActive(v *bool) *OpenAIOAuthDailySessionAffinityUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the OpenAIOAuthDailySessionAffinityMutation object of the builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) Mutation() *OpenAIOAuthDailySessionAffinityMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIOAuthDailySessionAffinityUpdate builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) Where(ps ...predicate.OpenAIOAuthDailySessionAffinity) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) Select(field string, fields ...string) *OpenAIOAuthDailySessionAffinityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIOAuthDailySessionAffinity entity.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) Save(ctx context.Context) (*OpenAIOAuthDailySessionAffinity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) SaveX(ctx context.Context) *OpenAIOAuthDailySessionAffinity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionaffinity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := openaioauthdailysessionaffinity.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) check() error {
	if v, ok := _u.mutation.LogicalSessionKey(); ok {
		if err := openaioauthdailysessionaffinity.LogicalSessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_session_key", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.logical_session_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionaffinity.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.business_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := openaioauthdailysessionaffinity.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSessionID(); ok {
		if err := openaioauthdailysessionaffinity.StreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.stream_session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthDailySessionAffinityUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIOAuthDailySessionAffinity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthdailysessionaffinity.Table, openaioauthdailysessionaffinity.Columns, sqlgraph.NewFieldSpec(openaioauthdailysessionaffinity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIOAuthDailySessionAffinity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaioauthdailysessionaffinity.FieldID)
		for _, f := range fields {
			if !openaioauthdailysessionaffinity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaioauthdailysessionaffinity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LogicalSessionKey(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLogicalSessionKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.SlotIndex(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotIndex(); ok {
		_spec.AddField(openaioauthdailysessionaffinity.FieldSlotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StreamSessionID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldStreamSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldActive, field.TypeBool, value)
	}
	_node = &OpenAIOAuthDailySessionAffinity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthdailysessionaffinity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
