// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthsyncsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIOAuthSyncSessionUpdate is the builder for updating OpenAIOAuthSyncSession entities.
type OpenAIOAuthSyncSessionUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthSyncSessionMutation
}

// Where appends a list predicates to the OpenAIOAuthSyncSessionUpdate builder.
func (_u *OpenAIOAuthSyncSessionUpdate) Where(ps ...predicate.OpenAIOAuthSyncSession) *OpenAIOAuthSyncSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthSyncSessionUpdate) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthSyncSessionUpdate) SetAccountID(v int64) *OpenAIOAuthSyncSessionUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthSyncSessionUpdate) SetNillableAccountID(v *int64) *OpenAIOAuthSyncSessionUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthSyncSessionUpdate) AddAccountID(v int64) *OpenAIOAuthSyncSessionUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *OpenAIOAuthSyncSessionUpdate) SetSessionID(v string) *OpenAIOAuthSyncSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *OpenAIOAuthSyncSessionUpdate) SetNillableSessionID(v *string) *OpenAIOAuthSyncSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// Mutation returns the OpenAIOAuthSyncSessionMutation object of the builder.
func (_u *OpenAIOAuthSyncSessionUpdate) Mutation() *OpenAIOAuthSyncSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIOAuthSyncSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthSyncSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIOAuthSyncSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthSyncSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthSyncSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthsyncsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthSyncSessionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := openaioauthsyncsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthSyncSession.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthSyncSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthsyncsession.Table, openaioauthsyncsession.Columns, sqlgraph.NewFieldSpec(openaioauthsyncsession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthsyncsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthsyncsession.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldSessionID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthsyncsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIOAuthSyncSessionUpdateOne is the builder for updating a single OpenAIOAuthSyncSession entity.
type OpenAIOAuthSyncSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIOAuthSyncSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SetAccountID(v int64) *OpenAIOAuthSyncSessionUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SetNillableAccountID(v *int64) *OpenAIOAuthSyncSessionUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthSyncSessionUpdateOne) AddAccountID(v int64) *OpenAIOAuthSyncSessionUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SetSessionID(v string) *OpenAIOAuthSyncSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SetNillableSessionID(v *string) *OpenAIOAuthSyncSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// Mutation returns the OpenAIOAuthSyncSessionMutation object of the builder.
func (_u *OpenAIOAuthSyncSessionUpdateOne) Mutation() *OpenAIOAuthSyncSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIOAuthSyncSessionUpdate builder.
func (_u *OpenAIOAuthSyncSessionUpdateOne) Where(ps ...predicate.OpenAIOAuthSyncSession) *OpenAIOAuthSyncSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIOAuthSyncSessionUpdateOne) Select(field string, fields ...string) *OpenAIOAuthSyncSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIOAuthSyncSession entity.
func (_u *OpenAIOAuthSyncSessionUpdateOne) Save(ctx context.Context) (*OpenAIOAuthSyncSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthSyncSessionUpdateOne) SaveX(ctx context.Context) *OpenAIOAuthSyncSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIOAuthSyncSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthSyncSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthSyncSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthsyncsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthSyncSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := openaioauthsyncsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthSyncSession.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthSyncSessionUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIOAuthSyncSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthsyncsession.Table, openaioauthsyncsession.Columns, sqlgraph.NewFieldSpec(openaioauthsyncsession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIOAuthSyncSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaioauthsyncsession.FieldID)
		for _, f := range fields {
			if !openaioauthsyncsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaioauthsyncsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthsyncsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthsyncsession.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldSessionID, field.TypeString, value)
	}
	_node = &OpenAIOAuthSyncSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthsyncsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
