// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionaffinity"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIOAuthDailySessionAffinityDelete is the builder for deleting a OpenAIOAuthDailySessionAffinity entity.
type OpenAIOAuthDailySessionAffinityDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthDailySessionAffinityMutation
}

// Where appends a list predicates to the OpenAIOAuthDailySessionAffinityDelete builder.
func (_d *OpenAIOAuthDailySessionAffinityDelete) Where(ps ...predicate.OpenAIOAuthDailySessionAffinity) *OpenAIOAuthDailySessionAffinityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIOAuthDailySessionAffinityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthDailySessionAffinityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIOAuthDailySessionAffinityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaioauthdailysessionaffinity.Table, sqlgraph.NewFieldSpec(openaioauthdailysessionaffinity.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIOAuthDailySessionAffinityDeleteOne is the builder for deleting a single OpenAIOAuthDailySessionAffinity entity.
type OpenAIOAuthDailySessionAffinityDeleteOne struct {
	_d *OpenAIOAuthDailySessionAffinityDelete
}

// Where appends a list predicates to the OpenAIOAuthDailySessionAffinityDelete builder.
func (_d *OpenAIOAuthDailySessionAffinityDeleteOne) Where(ps ...predicate.OpenAIOAuthDailySessionAffinity) *OpenAIOAuthDailySessionAffinityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIOAuthDailySessionAffinityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaioauthdailysessionaffinity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthDailySessionAffinityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
