// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionaffinity"
)

// OpenAIOAuthDailySessionAffinityCreate is the builder for creating a OpenAIOAuthDailySessionAffinity entity.
type OpenAIOAuthDailySessionAffinityCreate struct {
	config
	mutation *OpenAIOAuthDailySessionAffinityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetCreatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetNillableCreatedAt(v *time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetNillableAPIKeyID(v *int64) *OpenAIOAuthDailySessionAffinityCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetLogicalSessionKey(v)
	return _c
}

// SetBusinessDate sets the "business_date" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetBusinessDate(v)
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetSlotIndex sets the "slot_index" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetSlotIndex(v)
	return _c
}

// SetStreamSessionID sets the "stream_session_id" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetStreamSessionID(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetNillableLastSeenAt(v *time.Time) *OpenAIOAuthDailySessionAffinityCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetActive(v bool) *OpenAIOAuthDailySessionAffinityCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SetNillableActive(v *bool) *OpenAIOAuthDailySessionAffinityCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// Mutation returns the OpenAIOAuthDailySessionAffinityMutation object of the builder.
func (_c *OpenAIOAuthDailySessionAffinityCreate) Mutation() *OpenAIOAuthDailySessionAffinityMutation {
	return _c.mutation
}

// Save creates the OpenAIOAuthDailySessionAffinity in the database.
func (_c *OpenAIOAuthDailySessionAffinityCreate) Save(ctx context.Context) (*OpenAIOAuthDailySessionAffinity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIOAuthDailySessionAffinityCreate) SaveX(ctx context.Context) *OpenAIOAuthDailySessionAffinity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthDailySessionAffinityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionAffinityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIOAuthDailySessionAffinityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaioauthdailysessionaffinity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionaffinity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		v := openaioauthdailysessionaffinity.DefaultAPIKeyID
		_c.mutation.SetAPIKeyID(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := openaioauthdailysessionaffinity.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := openaioauthdailysessionaffinity.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIOAuthDailySessionAffinityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.account_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.api_key_id"`)}
	}
	if _, ok := _c.mutation.LogicalSessionKey(); !ok {
		return &ValidationError{Name: "logical_session_key", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.logical_session_key"`)}
	}
	if v, ok := _c.mutation.LogicalSessionKey(); ok {
		if err := openaioauthdailysessionaffinity.LogicalSessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_session_key", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.logical_session_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BusinessDate(); !ok {
		return &ValidationError{Name: "business_date", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.business_date"`)}
	}
	if v, ok := _c.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionaffinity.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.business_date": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.generation"`)}
	}
	if v, ok := _c.mutation.Generation(); ok {
		if err := openaioauthdailysessionaffinity.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.generation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SlotIndex(); !ok {
		return &ValidationError{Name: "slot_index", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.slot_index"`)}
	}
	if _, ok := _c.mutation.StreamSessionID(); !ok {
		return &ValidationError{Name: "stream_session_id", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.stream_session_id"`)}
	}
	if v, ok := _c.mutation.StreamSessionID(); ok {
		if err := openaioauthdailysessionaffinity.StreamSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionAffinity.stream_session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.last_seen_at"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionAffinity.active"`)}
	}
	return nil
}

func (_c *OpenAIOAuthDailySessionAffinityCreate) sqlSave(ctx context.Context) (*OpenAIOAuthDailySessionAffinity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIOAuthDailySessionAffinityCreate) createSpec() (*OpenAIOAuthDailySessionAffinity, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIOAuthDailySessionAffinity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaioauthdailysessionaffinity.Table, sqlgraph.NewFieldSpec(openaioauthdailysessionaffinity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.LogicalSessionKey(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLogicalSessionKey, field.TypeString, value)
		_node.LogicalSessionKey = value
	}
	if value, ok := _c.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldBusinessDate, field.TypeString, value)
		_node.BusinessDate = value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldGeneration, field.TypeString, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.SlotIndex(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldSlotIndex, field.TypeInt, value)
		_node.SlotIndex = value
	}
	if value, ok := _c.mutation.StreamSessionID(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldStreamSessionID, field.TypeString, value)
		_node.StreamSessionID = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(openaioauthdailysessionaffinity.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthDailySessionAffinityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionAffinityCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthDailySessionAffinityUpsertOne {
	_c.conflict = opts
	return &OpenAIOAuthDailySessionAffinityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionAffinityCreate) OnConflictColumns(columns ...string) *OpenAIOAuthDailySessionAffinityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthDailySessionAffinityUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIOAuthDailySessionAffinityUpsertOne is the builder for "upsert"-ing
	//  one OpenAIOAuthDailySessionAffinity node.
	OpenAIOAuthDailySessionAffinityUpsertOne struct {
		create *OpenAIOAuthDailySessionAffinityCreate
	}

	// OpenAIOAuthDailySessionAffinityUpsert is the "OnConflict" setter.
	OpenAIOAuthDailySessionAffinityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateUpdatedAt() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateAccountID() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) AddAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Add(openaioauthdailysessionaffinity.FieldAccountID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateAPIKeyID() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) AddAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Add(openaioauthdailysessionaffinity.FieldAPIKeyID, v)
	return u
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldLogicalSessionKey, v)
	return u
}

// UpdateLogicalSessionKey sets the "logical_session_key" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateLogicalSessionKey() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldLogicalSessionKey)
	return u
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldBusinessDate, v)
	return u
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateBusinessDate() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldBusinessDate)
	return u
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldGeneration, v)
	return u
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateGeneration() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldGeneration)
	return u
}

// SetSlotIndex sets the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldSlotIndex, v)
	return u
}

// UpdateSlotIndex sets the "slot_index" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateSlotIndex() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldSlotIndex)
	return u
}

// AddSlotIndex adds v to the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) AddSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Add(openaioauthdailysessionaffinity.FieldSlotIndex, v)
	return u
}

// SetStreamSessionID sets the "stream_session_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldStreamSessionID, v)
	return u
}

// UpdateStreamSessionID sets the "stream_session_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateStreamSessionID() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldStreamSessionID)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateLastSeenAt() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldLastSeenAt)
	return u
}

// SetActive sets the "active" field.
func (u *OpenAIOAuthDailySessionAffinityUpsert) SetActive(v bool) *OpenAIOAuthDailySessionAffinityUpsert {
	u.Set(openaioauthdailysessionaffinity.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsert) UpdateActive() *OpenAIOAuthDailySessionAffinityUpsert {
	u.SetExcluded(openaioauthdailysessionaffinity.FieldActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateNewValues() *OpenAIOAuthDailySessionAffinityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaioauthdailysessionaffinity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) Ignore() *OpenAIOAuthDailySessionAffinityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) DoNothing() *OpenAIOAuthDailySessionAffinityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthDailySessionAffinityCreate.OnConflict
// documentation for more info.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) Update(set func(*OpenAIOAuthDailySessionAffinityUpsert)) *OpenAIOAuthDailySessionAffinityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthDailySessionAffinityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateUpdatedAt() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) AddAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateAccountID() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateAccountID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) AddAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateAPIKeyID() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetLogicalSessionKey(v)
	})
}

// UpdateLogicalSessionKey sets the "logical_session_key" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateLogicalSessionKey() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateLogicalSessionKey()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateBusinessDate() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateGeneration() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateGeneration()
	})
}

// SetSlotIndex sets the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetSlotIndex(v)
	})
}

// AddSlotIndex adds v to the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) AddSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddSlotIndex(v)
	})
}

// UpdateSlotIndex sets the "slot_index" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateSlotIndex() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateSlotIndex()
	})
}

// SetStreamSessionID sets the "stream_session_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetStreamSessionID(v)
	})
}

// UpdateStreamSessionID sets the "stream_session_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateStreamSessionID() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateStreamSessionID()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateLastSeenAt() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetActive sets the "active" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) SetActive(v bool) *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) UpdateActive() *OpenAIOAuthDailySessionAffinityUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthDailySessionAffinityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionAffinityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIOAuthDailySessionAffinityCreateBulk is the builder for creating many OpenAIOAuthDailySessionAffinity entities in bulk.
type OpenAIOAuthDailySessionAffinityCreateBulk struct {
	config
	err      error
	builders []*OpenAIOAuthDailySessionAffinityCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIOAuthDailySessionAffinity entities in the database.
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) Save(ctx context.Context) ([]*OpenAIOAuthDailySessionAffinity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIOAuthDailySessionAffinity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIOAuthDailySessionAffinityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) SaveX(ctx context.Context) []*OpenAIOAuthDailySessionAffinity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthDailySessionAffinity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthDailySessionAffinityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	_c.conflict = opts
	return &OpenAIOAuthDailySessionAffinityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionAffinityCreateBulk) OnConflictColumns(columns ...string) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthDailySessionAffinityUpsertBulk{
		create: _c,
	}
}

// OpenAIOAuthDailySessionAffinityUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIOAuthDailySessionAffinity nodes.
type OpenAIOAuthDailySessionAffinityUpsertBulk struct {
	create *OpenAIOAuthDailySessionAffinityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateNewValues() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaioauthdailysessionaffinity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionAffinity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) Ignore() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) DoNothing() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthDailySessionAffinityCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) Update(set func(*OpenAIOAuthDailySessionAffinityUpsert)) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthDailySessionAffinityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateUpdatedAt() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) AddAccountID(v int64) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateAccountID() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateAccountID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) AddAPIKeyID(v int64) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateAPIKeyID() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetLogicalSessionKey sets the "logical_session_key" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetLogicalSessionKey(v string) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetLogicalSessionKey(v)
	})
}

// UpdateLogicalSessionKey sets the "logical_session_key" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateLogicalSessionKey() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateLogicalSessionKey()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetBusinessDate(v string) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateBusinessDate() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetGeneration(v string) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateGeneration() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateGeneration()
	})
}

// SetSlotIndex sets the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetSlotIndex(v)
	})
}

// AddSlotIndex adds v to the "slot_index" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) AddSlotIndex(v int) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.AddSlotIndex(v)
	})
}

// UpdateSlotIndex sets the "slot_index" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateSlotIndex() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateSlotIndex()
	})
}

// SetStreamSessionID sets the "stream_session_id" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetStreamSessionID(v string) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetStreamSessionID(v)
	})
}

// UpdateStreamSessionID sets the "stream_session_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateStreamSessionID() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateStreamSessionID()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetLastSeenAt(v time.Time) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateLastSeenAt() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetActive sets the "active" field.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) SetActive(v bool) *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) UpdateActive() *OpenAIOAuthDailySessionAffinityUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionAffinityUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIOAuthDailySessionAffinityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthDailySessionAffinityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionAffinityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
