// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthsyncsession"
)

// OpenAIOAuthSyncSessionCreate is the builder for creating a OpenAIOAuthSyncSession entity.
type OpenAIOAuthSyncSessionCreate struct {
	config
	mutation *OpenAIOAuthSyncSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIOAuthSyncSessionCreate) SetCreatedAt(v time.Time) *OpenAIOAuthSyncSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIOAuthSyncSessionCreate) SetNillableCreatedAt(v *time.Time) *OpenAIOAuthSyncSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIOAuthSyncSessionCreate) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIOAuthSyncSessionCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIOAuthSyncSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIOAuthSyncSessionCreate) SetAccountID(v int64) *OpenAIOAuthSyncSessionCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *OpenAIOAuthSyncSessionCreate) SetSessionID(v string) *OpenAIOAuthSyncSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// Mutation returns the OpenAIOAuthSyncSessionMutation object of the builder.
func (_c *OpenAIOAuthSyncSessionCreate) Mutation() *OpenAIOAuthSyncSessionMutation {
	return _c.mutation
}

// Save creates the OpenAIOAuthSyncSession in the database.
func (_c *OpenAIOAuthSyncSessionCreate) Save(ctx context.Context) (*OpenAIOAuthSyncSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIOAuthSyncSessionCreate) SaveX(ctx context.Context) *OpenAIOAuthSyncSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthSyncSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthSyncSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIOAuthSyncSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaioauthsyncsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaioauthsyncsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIOAuthSyncSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIOAuthSyncSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIOAuthSyncSession.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIOAuthSyncSession.account_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "OpenAIOAuthSyncSession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := openaioauthsyncsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthSyncSession.session_id": %w`, err)}
		}
	}
	return nil
}

func (_c *OpenAIOAuthSyncSessionCreate) sqlSave(ctx context.Context) (*OpenAIOAuthSyncSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIOAuthSyncSessionCreate) createSpec() (*OpenAIOAuthSyncSession, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIOAuthSyncSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaioauthsyncsession.Table, sqlgraph.NewFieldSpec(openaioauthsyncsession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaioauthsyncsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthsyncsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(openaioauthsyncsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthSyncSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthSyncSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthSyncSessionCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthSyncSessionUpsertOne {
	_c.conflict = opts
	return &OpenAIOAuthSyncSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthSyncSessionCreate) OnConflictColumns(columns ...string) *OpenAIOAuthSyncSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthSyncSessionUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIOAuthSyncSessionUpsertOne is the builder for "upsert"-ing
	//  one OpenAIOAuthSyncSession node.
	OpenAIOAuthSyncSessionUpsertOne struct {
		create *OpenAIOAuthSyncSessionCreate
	}

	// OpenAIOAuthSyncSessionUpsert is the "OnConflict" setter.
	OpenAIOAuthSyncSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthSyncSessionUpsert) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionUpsert {
	u.Set(openaioauthsyncsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsert) UpdateUpdatedAt() *OpenAIOAuthSyncSessionUpsert {
	u.SetExcluded(openaioauthsyncsession.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsert) SetAccountID(v int64) *OpenAIOAuthSyncSessionUpsert {
	u.Set(openaioauthsyncsession.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsert) UpdateAccountID() *OpenAIOAuthSyncSessionUpsert {
	u.SetExcluded(openaioauthsyncsession.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsert) AddAccountID(v int64) *OpenAIOAuthSyncSessionUpsert {
	u.Add(openaioauthsyncsession.FieldAccountID, v)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *OpenAIOAuthSyncSessionUpsert) SetSessionID(v string) *OpenAIOAuthSyncSessionUpsert {
	u.Set(openaioauthsyncsession.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsert) UpdateSessionID() *OpenAIOAuthSyncSessionUpsert {
	u.SetExcluded(openaioauthsyncsession.FieldSessionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthSyncSessionUpsertOne) UpdateNewValues() *OpenAIOAuthSyncSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaioauthsyncsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIOAuthSyncSessionUpsertOne) Ignore() *OpenAIOAuthSyncSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthSyncSessionUpsertOne) DoNothing() *OpenAIOAuthSyncSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthSyncSessionCreate.OnConflict
// documentation for more info.
func (u *OpenAIOAuthSyncSessionUpsertOne) Update(set func(*OpenAIOAuthSyncSessionUpsert)) *OpenAIOAuthSyncSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthSyncSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthSyncSessionUpsertOne) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertOne) UpdateUpdatedAt() *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsertOne) SetAccountID(v int64) *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsertOne) AddAccountID(v int64) *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertOne) UpdateAccountID() *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateAccountID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *OpenAIOAuthSyncSessionUpsertOne) SetSessionID(v string) *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertOne) UpdateSessionID() *OpenAIOAuthSyncSessionUpsertOne {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateSessionID()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthSyncSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthSyncSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthSyncSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIOAuthSyncSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIOAuthSyncSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIOAuthSyncSessionCreateBulk is the builder for creating many OpenAIOAuthSyncSession entities in bulk.
type OpenAIOAuthSyncSessionCreateBulk struct {
	config
	err      error
	builders []*OpenAIOAuthSyncSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIOAuthSyncSession entities in the database.
func (_c *OpenAIOAuthSyncSessionCreateBulk) Save(ctx context.Context) ([]*OpenAIOAuthSyncSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIOAuthSyncSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIOAuthSyncSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIOAuthSyncSessionCreateBulk) SaveX(ctx context.Context) []*OpenAIOAuthSyncSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthSyncSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthSyncSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthSyncSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthSyncSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthSyncSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthSyncSessionUpsertBulk {
	_c.conflict = opts
	return &OpenAIOAuthSyncSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthSyncSessionCreateBulk) OnConflictColumns(columns ...string) *OpenAIOAuthSyncSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthSyncSessionUpsertBulk{
		create: _c,
	}
}

// OpenAIOAuthSyncSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIOAuthSyncSession nodes.
type OpenAIOAuthSyncSessionUpsertBulk struct {
	create *OpenAIOAuthSyncSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthSyncSessionUpsertBulk) UpdateNewValues() *OpenAIOAuthSyncSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaioauthsyncsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthSyncSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIOAuthSyncSessionUpsertBulk) Ignore() *OpenAIOAuthSyncSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthSyncSessionUpsertBulk) DoNothing() *OpenAIOAuthSyncSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthSyncSessionCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIOAuthSyncSessionUpsertBulk) Update(set func(*OpenAIOAuthSyncSessionUpsert)) *OpenAIOAuthSyncSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthSyncSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthSyncSessionUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertBulk) UpdateUpdatedAt() *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsertBulk) SetAccountID(v int64) *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthSyncSessionUpsertBulk) AddAccountID(v int64) *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertBulk) UpdateAccountID() *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateAccountID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *OpenAIOAuthSyncSessionUpsertBulk) SetSessionID(v string) *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *OpenAIOAuthSyncSessionUpsertBulk) UpdateSessionID() *OpenAIOAuthSyncSessionUpsertBulk {
	return u.Update(func(s *OpenAIOAuthSyncSessionUpsert) {
		s.UpdateSessionID()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthSyncSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIOAuthSyncSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthSyncSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthSyncSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
