// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthsyncsession"
)

// OpenAIOAuthSyncSession is the model entity for the OpenAIOAuthSyncSession schema.
type OpenAIOAuthSyncSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID    string `json:"session_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIOAuthSyncSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaioauthsyncsession.FieldID, openaioauthsyncsession.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case openaioauthsyncsession.FieldSessionID:
			values[i] = new(sql.NullString)
		case openaioauthsyncsession.FieldCreatedAt, openaioauthsyncsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIOAuthSyncSession fields.
func (_m *OpenAIOAuthSyncSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaioauthsyncsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaioauthsyncsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaioauthsyncsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaioauthsyncsession.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaioauthsyncsession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIOAuthSyncSession.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIOAuthSyncSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIOAuthSyncSession.
// Note that you need to call OpenAIOAuthSyncSession.Unwrap() before calling this method if this OpenAIOAuthSyncSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIOAuthSyncSession) Update() *OpenAIOAuthSyncSessionUpdateOne {
	return NewOpenAIOAuthSyncSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIOAuthSyncSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIOAuthSyncSession) Unwrap() *OpenAIOAuthSyncSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIOAuthSyncSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIOAuthSyncSession) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIOAuthSyncSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIOAuthSyncSessions is a parsable slice of OpenAIOAuthSyncSession.
type OpenAIOAuthSyncSessions []*OpenAIOAuthSyncSession
