// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionpool"
)

// OpenAIOAuthDailySessionPoolCreate is the builder for creating a OpenAIOAuthDailySessionPool entity.
type OpenAIOAuthDailySessionPoolCreate struct {
	config
	mutation *OpenAIOAuthDailySessionPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetCreatedAt(v time.Time) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetNillableCreatedAt(v *time.Time) *OpenAIOAuthDailySessionPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIOAuthDailySessionPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetBusinessDate sets the "business_date" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetBusinessDate(v)
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetGeneration(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetStreamSession0 sets the "stream_session_0" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetStreamSession0(v)
	return _c
}

// SetStreamSession1 sets the "stream_session_1" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetStreamSession1(v)
	return _c
}

// SetStreamSession2 sets the "stream_session_2" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetStreamSession2(v)
	return _c
}

// SetSyncSession sets the "sync_session" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetSyncSession(v)
	return _c
}

// SetActiveStreams sets the "active_streams" field.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolCreate {
	_c.mutation.SetActiveStreams(v)
	return _c
}

// SetNillableActiveStreams sets the "active_streams" field if the given value is not nil.
func (_c *OpenAIOAuthDailySessionPoolCreate) SetNillableActiveStreams(v *int) *OpenAIOAuthDailySessionPoolCreate {
	if v != nil {
		_c.SetActiveStreams(*v)
	}
	return _c
}

// Mutation returns the OpenAIOAuthDailySessionPoolMutation object of the builder.
func (_c *OpenAIOAuthDailySessionPoolCreate) Mutation() *OpenAIOAuthDailySessionPoolMutation {
	return _c.mutation
}

// Save creates the OpenAIOAuthDailySessionPool in the database.
func (_c *OpenAIOAuthDailySessionPoolCreate) Save(ctx context.Context) (*OpenAIOAuthDailySessionPool, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIOAuthDailySessionPoolCreate) SaveX(ctx context.Context) *OpenAIOAuthDailySessionPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthDailySessionPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIOAuthDailySessionPoolCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaioauthdailysessionpool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionpool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ActiveStreams(); !ok {
		v := openaioauthdailysessionpool.DefaultActiveStreams
		_c.mutation.SetActiveStreams(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIOAuthDailySessionPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.account_id"`)}
	}
	if _, ok := _c.mutation.BusinessDate(); !ok {
		return &ValidationError{Name: "business_date", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.business_date"`)}
	}
	if v, ok := _c.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionpool.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.business_date": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.generation"`)}
	}
	if v, ok := _c.mutation.Generation(); ok {
		if err := openaioauthdailysessionpool.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.generation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamSession0(); !ok {
		return &ValidationError{Name: "stream_session_0", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.stream_session_0"`)}
	}
	if v, ok := _c.mutation.StreamSession0(); ok {
		if err := openaioauthdailysessionpool.StreamSession0Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_0", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_0": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamSession1(); !ok {
		return &ValidationError{Name: "stream_session_1", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.stream_session_1"`)}
	}
	if v, ok := _c.mutation.StreamSession1(); ok {
		if err := openaioauthdailysessionpool.StreamSession1Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_1", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_1": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamSession2(); !ok {
		return &ValidationError{Name: "stream_session_2", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.stream_session_2"`)}
	}
	if v, ok := _c.mutation.StreamSession2(); ok {
		if err := openaioauthdailysessionpool.StreamSession2Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_2", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_2": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncSession(); !ok {
		return &ValidationError{Name: "sync_session", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.sync_session"`)}
	}
	if v, ok := _c.mutation.SyncSession(); ok {
		if err := openaioauthdailysessionpool.SyncSessionValidator(v); err != nil {
			return &ValidationError{Name: "sync_session", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.sync_session": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActiveStreams(); !ok {
		return &ValidationError{Name: "active_streams", err: errors.New(`ent: missing required field "OpenAIOAuthDailySessionPool.active_streams"`)}
	}
	return nil
}

func (_c *OpenAIOAuthDailySessionPoolCreate) sqlSave(ctx context.Context) (*OpenAIOAuthDailySessionPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIOAuthDailySessionPoolCreate) createSpec() (*OpenAIOAuthDailySessionPool, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIOAuthDailySessionPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaioauthdailysessionpool.Table, sqlgraph.NewFieldSpec(openaioauthdailysessionpool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldBusinessDate, field.TypeString, value)
		_node.BusinessDate = value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldGeneration, field.TypeString, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.StreamSession0(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession0, field.TypeString, value)
		_node.StreamSession0 = value
	}
	if value, ok := _c.mutation.StreamSession1(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession1, field.TypeString, value)
		_node.StreamSession1 = value
	}
	if value, ok := _c.mutation.StreamSession2(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession2, field.TypeString, value)
		_node.StreamSession2 = value
	}
	if value, ok := _c.mutation.SyncSession(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldSyncSession, field.TypeString, value)
		_node.SyncSession = value
	}
	if value, ok := _c.mutation.ActiveStreams(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldActiveStreams, field.TypeInt, value)
		_node.ActiveStreams = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthDailySessionPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionPoolCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthDailySessionPoolUpsertOne {
	_c.conflict = opts
	return &OpenAIOAuthDailySessionPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionPoolCreate) OnConflictColumns(columns ...string) *OpenAIOAuthDailySessionPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthDailySessionPoolUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIOAuthDailySessionPoolUpsertOne is the builder for "upsert"-ing
	//  one OpenAIOAuthDailySessionPool node.
	OpenAIOAuthDailySessionPoolUpsertOne struct {
		create *OpenAIOAuthDailySessionPoolCreate
	}

	// OpenAIOAuthDailySessionPoolUpsert is the "OnConflict" setter.
	OpenAIOAuthDailySessionPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateUpdatedAt() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateAccountID() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) AddAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsert {
	u.Add(openaioauthdailysessionpool.FieldAccountID, v)
	return u
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldBusinessDate, v)
	return u
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateBusinessDate() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldBusinessDate)
	return u
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetGeneration(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldGeneration, v)
	return u
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateGeneration() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldGeneration)
	return u
}

// SetStreamSession0 sets the "stream_session_0" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldStreamSession0, v)
	return u
}

// UpdateStreamSession0 sets the "stream_session_0" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateStreamSession0() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldStreamSession0)
	return u
}

// SetStreamSession1 sets the "stream_session_1" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldStreamSession1, v)
	return u
}

// UpdateStreamSession1 sets the "stream_session_1" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateStreamSession1() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldStreamSession1)
	return u
}

// SetStreamSession2 sets the "stream_session_2" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldStreamSession2, v)
	return u
}

// UpdateStreamSession2 sets the "stream_session_2" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateStreamSession2() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldStreamSession2)
	return u
}

// SetSyncSession sets the "sync_session" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldSyncSession, v)
	return u
}

// UpdateSyncSession sets the "sync_session" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateSyncSession() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldSyncSession)
	return u
}

// SetActiveStreams sets the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsert {
	u.Set(openaioauthdailysessionpool.FieldActiveStreams, v)
	return u
}

// UpdateActiveStreams sets the "active_streams" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsert) UpdateActiveStreams() *OpenAIOAuthDailySessionPoolUpsert {
	u.SetExcluded(openaioauthdailysessionpool.FieldActiveStreams)
	return u
}

// AddActiveStreams adds v to the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsert) AddActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsert {
	u.Add(openaioauthdailysessionpool.FieldActiveStreams, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateNewValues() *OpenAIOAuthDailySessionPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaioauthdailysessionpool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIOAuthDailySessionPoolUpsertOne) Ignore() *OpenAIOAuthDailySessionPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) DoNothing() *OpenAIOAuthDailySessionPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthDailySessionPoolCreate.OnConflict
// documentation for more info.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) Update(set func(*OpenAIOAuthDailySessionPoolUpsert)) *OpenAIOAuthDailySessionPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthDailySessionPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateUpdatedAt() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) AddAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateAccountID() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateAccountID()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateBusinessDate() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetGeneration(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateGeneration() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateGeneration()
	})
}

// SetStreamSession0 sets the "stream_session_0" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession0(v)
	})
}

// UpdateStreamSession0 sets the "stream_session_0" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateStreamSession0() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession0()
	})
}

// SetStreamSession1 sets the "stream_session_1" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession1(v)
	})
}

// UpdateStreamSession1 sets the "stream_session_1" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateStreamSession1() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession1()
	})
}

// SetStreamSession2 sets the "stream_session_2" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession2(v)
	})
}

// UpdateStreamSession2 sets the "stream_session_2" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateStreamSession2() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession2()
	})
}

// SetSyncSession sets the "sync_session" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetSyncSession(v)
	})
}

// UpdateSyncSession sets the "sync_session" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateSyncSession() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateSyncSession()
	})
}

// SetActiveStreams sets the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetActiveStreams(v)
	})
}

// AddActiveStreams adds v to the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) AddActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.AddActiveStreams(v)
	})
}

// UpdateActiveStreams sets the "active_streams" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) UpdateActiveStreams() *OpenAIOAuthDailySessionPoolUpsertOne {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateActiveStreams()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthDailySessionPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIOAuthDailySessionPoolCreateBulk is the builder for creating many OpenAIOAuthDailySessionPool entities in bulk.
type OpenAIOAuthDailySessionPoolCreateBulk struct {
	config
	err      error
	builders []*OpenAIOAuthDailySessionPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIOAuthDailySessionPool entities in the database.
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) Save(ctx context.Context) ([]*OpenAIOAuthDailySessionPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIOAuthDailySessionPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIOAuthDailySessionPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) SaveX(ctx context.Context) []*OpenAIOAuthDailySessionPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthDailySessionPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthDailySessionPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthDailySessionPoolUpsertBulk {
	_c.conflict = opts
	return &OpenAIOAuthDailySessionPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthDailySessionPoolCreateBulk) OnConflictColumns(columns ...string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthDailySessionPoolUpsertBulk{
		create: _c,
	}
}

// OpenAIOAuthDailySessionPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIOAuthDailySessionPool nodes.
type OpenAIOAuthDailySessionPoolUpsertBulk struct {
	create *OpenAIOAuthDailySessionPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateNewValues() *OpenAIOAuthDailySessionPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaioauthdailysessionpool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthDailySessionPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) Ignore() *OpenAIOAuthDailySessionPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) DoNothing() *OpenAIOAuthDailySessionPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthDailySessionPoolCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) Update(set func(*OpenAIOAuthDailySessionPoolUpsert)) *OpenAIOAuthDailySessionPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthDailySessionPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateUpdatedAt() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) AddAccountID(v int64) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateAccountID() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateAccountID()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateBusinessDate() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetGeneration sets the "generation" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetGeneration(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateGeneration() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateGeneration()
	})
}

// SetStreamSession0 sets the "stream_session_0" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession0(v)
	})
}

// UpdateStreamSession0 sets the "stream_session_0" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateStreamSession0() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession0()
	})
}

// SetStreamSession1 sets the "stream_session_1" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession1(v)
	})
}

// UpdateStreamSession1 sets the "stream_session_1" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateStreamSession1() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession1()
	})
}

// SetStreamSession2 sets the "stream_session_2" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetStreamSession2(v)
	})
}

// UpdateStreamSession2 sets the "stream_session_2" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateStreamSession2() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateStreamSession2()
	})
}

// SetSyncSession sets the "sync_session" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetSyncSession(v)
	})
}

// UpdateSyncSession sets the "sync_session" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateSyncSession() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateSyncSession()
	})
}

// SetActiveStreams sets the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.SetActiveStreams(v)
	})
}

// AddActiveStreams adds v to the "active_streams" field.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) AddActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.AddActiveStreams(v)
	})
}

// UpdateActiveStreams sets the "active_streams" field to the value that was provided on create.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) UpdateActiveStreams() *OpenAIOAuthDailySessionPoolUpsertBulk {
	return u.Update(func(s *OpenAIOAuthDailySessionPoolUpsert) {
		s.UpdateActiveStreams()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIOAuthDailySessionPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthDailySessionPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthDailySessionPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
