// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionpool"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIOAuthDailySessionPoolUpdate is the builder for updating OpenAIOAuthDailySessionPool entities.
type OpenAIOAuthDailySessionPoolUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthDailySessionPoolMutation
}

// Where appends a list predicates to the OpenAIOAuthDailySessionPoolUpdate builder.
func (_u *OpenAIOAuthDailySessionPoolUpdate) Where(ps ...predicate.OpenAIOAuthDailySessionPool) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableAccountID(v *int64) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) AddAccountID(v int64) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBusinessDate sets the "business_date" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetBusinessDate(v)
	return _u
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableBusinessDate(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetBusinessDate(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetGeneration(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableGeneration(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetStreamSession0 sets the "stream_session_0" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetStreamSession0(v)
	return _u
}

// SetNillableStreamSession0 sets the "stream_session_0" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableStreamSession0(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetStreamSession0(*v)
	}
	return _u
}

// SetStreamSession1 sets the "stream_session_1" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetStreamSession1(v)
	return _u
}

// SetNillableStreamSession1 sets the "stream_session_1" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableStreamSession1(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetStreamSession1(*v)
	}
	return _u
}

// SetStreamSession2 sets the "stream_session_2" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetStreamSession2(v)
	return _u
}

// SetNillableStreamSession2 sets the "stream_session_2" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableStreamSession2(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetStreamSession2(*v)
	}
	return _u
}

// SetSyncSession sets the "sync_session" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.SetSyncSession(v)
	return _u
}

// SetNillableSyncSession sets the "sync_session" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableSyncSession(v *string) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetSyncSession(*v)
	}
	return _u
}

// SetActiveStreams sets the "active_streams" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.ResetActiveStreams()
	_u.mutation.SetActiveStreams(v)
	return _u
}

// SetNillableActiveStreams sets the "active_streams" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SetNillableActiveStreams(v *int) *OpenAIOAuthDailySessionPoolUpdate {
	if v != nil {
		_u.SetActiveStreams(*v)
	}
	return _u
}

// AddActiveStreams adds value to the "active_streams" field.
func (_u *OpenAIOAuthDailySessionPoolUpdate) AddActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpdate {
	_u.mutation.AddActiveStreams(v)
	return _u
}

// Mutation returns the OpenAIOAuthDailySessionPoolMutation object of the builder.
func (_u *OpenAIOAuthDailySessionPoolUpdate) Mutation() *OpenAIOAuthDailySessionPoolMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIOAuthDailySessionPoolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIOAuthDailySessionPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthDailySessionPoolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthDailySessionPoolUpdate) check() error {
	if v, ok := _u.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionpool.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.business_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := openaioauthdailysessionpool.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession0(); ok {
		if err := openaioauthdailysessionpool.StreamSession0Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_0", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession1(); ok {
		if err := openaioauthdailysessionpool.StreamSession1Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_1", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession2(); ok {
		if err := openaioauthdailysessionpool.StreamSession2Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_2", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncSession(); ok {
		if err := openaioauthdailysessionpool.SyncSessionValidator(v); err != nil {
			return &ValidationError{Name: "sync_session", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.sync_session": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthDailySessionPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthdailysessionpool.Table, openaioauthdailysessionpool.Columns, sqlgraph.NewFieldSpec(openaioauthdailysessionpool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthdailysessionpool.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession0(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession0, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession1(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession1, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession2(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession2, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncSession(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldSyncSession, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveStreams(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldActiveStreams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveStreams(); ok {
		_spec.AddField(openaioauthdailysessionpool.FieldActiveStreams, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthdailysessionpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIOAuthDailySessionPoolUpdateOne is the builder for updating a single OpenAIOAuthDailySessionPool entity.
type OpenAIOAuthDailySessionPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIOAuthDailySessionPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetUpdatedAt(v time.Time) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetAccountID(v int64) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableAccountID(v *int64) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) AddAccountID(v int64) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBusinessDate sets the "business_date" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetBusinessDate(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetBusinessDate(v)
	return _u
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableBusinessDate(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetBusinessDate(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetGeneration(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableGeneration(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetStreamSession0 sets the "stream_session_0" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetStreamSession0(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetStreamSession0(v)
	return _u
}

// SetNillableStreamSession0 sets the "stream_session_0" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableStreamSession0(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetStreamSession0(*v)
	}
	return _u
}

// SetStreamSession1 sets the "stream_session_1" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetStreamSession1(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetStreamSession1(v)
	return _u
}

// SetNillableStreamSession1 sets the "stream_session_1" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableStreamSession1(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetStreamSession1(*v)
	}
	return _u
}

// SetStreamSession2 sets the "stream_session_2" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetStreamSession2(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetStreamSession2(v)
	return _u
}

// SetNillableStreamSession2 sets the "stream_session_2" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableStreamSession2(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetStreamSession2(*v)
	}
	return _u
}

// SetSyncSession sets the "sync_session" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetSyncSession(v string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.SetSyncSession(v)
	return _u
}

// SetNillableSyncSession sets the "sync_session" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableSyncSession(v *string) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetSyncSession(*v)
	}
	return _u
}

// SetActiveStreams sets the "active_streams" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.ResetActiveStreams()
	_u.mutation.SetActiveStreams(v)
	return _u
}

// SetNillableActiveStreams sets the "active_streams" field if the given value is not nil.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SetNillableActiveStreams(v *int) *OpenAIOAuthDailySessionPoolUpdateOne {
	if v != nil {
		_u.SetActiveStreams(*v)
	}
	return _u
}

// AddActiveStreams adds value to the "active_streams" field.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) AddActiveStreams(v int) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.AddActiveStreams(v)
	return _u
}

// Mutation returns the OpenAIOAuthDailySessionPoolMutation object of the builder.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) Mutation() *OpenAIOAuthDailySessionPoolMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIOAuthDailySessionPoolUpdate builder.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) Where(ps ...predicate.OpenAIOAuthDailySessionPool) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) Select(field string, fields ...string) *OpenAIOAuthDailySessionPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIOAuthDailySessionPool entity.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) Save(ctx context.Context) (*OpenAIOAuthDailySessionPool, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) SaveX(ctx context.Context) *OpenAIOAuthDailySessionPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthdailysessionpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthDailySessionPoolUpdateOne) check() error {
	if v, ok := _u.mutation.BusinessDate(); ok {
		if err := openaioauthdailysessionpool.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.business_date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := openaioauthdailysessionpool.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession0(); ok {
		if err := openaioauthdailysessionpool.StreamSession0Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_0", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession1(); ok {
		if err := openaioauthdailysessionpool.StreamSession1Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_1", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamSession2(); ok {
		if err := openaioauthdailysessionpool.StreamSession2Validator(v); err != nil {
			return &ValidationError{Name: "stream_session_2", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.stream_session_2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncSession(); ok {
		if err := openaioauthdailysessionpool.SyncSessionValidator(v); err != nil {
			return &ValidationError{Name: "sync_session", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthDailySessionPool.sync_session": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIOAuthDailySessionPoolUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIOAuthDailySessionPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthdailysessionpool.Table, openaioauthdailysessionpool.Columns, sqlgraph.NewFieldSpec(openaioauthdailysessionpool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIOAuthDailySessionPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaioauthdailysessionpool.FieldID)
		for _, f := range fields {
			if !openaioauthdailysessionpool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaioauthdailysessionpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaioauthdailysessionpool.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BusinessDate(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession0(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession0, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession1(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession1, field.TypeString, value)
	}
	if value, ok := _u.mutation.StreamSession2(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldStreamSession2, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncSession(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldSyncSession, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveStreams(); ok {
		_spec.SetField(openaioauthdailysessionpool.FieldActiveStreams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveStreams(); ok {
		_spec.AddField(openaioauthdailysessionpool.FieldActiveStreams, field.TypeInt, value)
	}
	_node = &OpenAIOAuthDailySessionPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthdailysessionpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
