// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaioauthdailysessionaffinity"
)

// OpenAIOAuthDailySessionAffinity is the model entity for the OpenAIOAuthDailySessionAffinity schema.
type OpenAIOAuthDailySessionAffinity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// LogicalSessionKey holds the value of the "logical_session_key" field.
	LogicalSessionKey string `json:"logical_session_key,omitempty"`
	// BusinessDate holds the value of the "business_date" field.
	BusinessDate string `json:"business_date,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation string `json:"generation,omitempty"`
	// SlotIndex holds the value of the "slot_index" field.
	SlotIndex int `json:"slot_index,omitempty"`
	// StreamSessionID holds the value of the "stream_session_id" field.
	StreamSessionID string `json:"stream_session_id,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Active holds the value of the "active" field.
	Active       bool `json:"active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIOAuthDailySessionAffinity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaioauthdailysessionaffinity.FieldActive:
			values[i] = new(sql.NullBool)
		case openaioauthdailysessionaffinity.FieldID, openaioauthdailysessionaffinity.FieldAccountID, openaioauthdailysessionaffinity.FieldAPIKeyID, openaioauthdailysessionaffinity.FieldSlotIndex:
			values[i] = new(sql.NullInt64)
		case openaioauthdailysessionaffinity.FieldLogicalSessionKey, openaioauthdailysessionaffinity.FieldBusinessDate, openaioauthdailysessionaffinity.FieldGeneration, openaioauthdailysessionaffinity.FieldStreamSessionID:
			values[i] = new(sql.NullString)
		case openaioauthdailysessionaffinity.FieldCreatedAt, openaioauthdailysessionaffinity.FieldUpdatedAt, openaioauthdailysessionaffinity.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIOAuthDailySessionAffinity fields.
func (_m *OpenAIOAuthDailySessionAffinity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaioauthdailysessionaffinity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaioauthdailysessionaffinity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaioauthdailysessionaffinity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaioauthdailysessionaffinity.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaioauthdailysessionaffinity.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case openaioauthdailysessionaffinity.FieldLogicalSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logical_session_key", values[i])
			} else if value.Valid {
				_m.LogicalSessionKey = value.String
			}
		case openaioauthdailysessionaffinity.FieldBusinessDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_date", values[i])
			} else if value.Valid {
				_m.BusinessDate = value.String
			}
		case openaioauthdailysessionaffinity.FieldGeneration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.String
			}
		case openaioauthdailysessionaffinity.FieldSlotIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field slot_index", values[i])
			} else if value.Valid {
				_m.SlotIndex = int(value.Int64)
			}
		case openaioauthdailysessionaffinity.FieldStreamSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_session_id", values[i])
			} else if value.Valid {
				_m.StreamSessionID = value.String
			}
		case openaioauthdailysessionaffinity.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case openaioauthdailysessionaffinity.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIOAuthDailySessionAffinity.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIOAuthDailySessionAffinity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIOAuthDailySessionAffinity.
// Note that you need to call OpenAIOAuthDailySessionAffinity.Unwrap() before calling this method if this OpenAIOAuthDailySessionAffinity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIOAuthDailySessionAffinity) Update() *OpenAIOAuthDailySessionAffinityUpdateOne {
	return NewOpenAIOAuthDailySessionAffinityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIOAuthDailySessionAffinity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIOAuthDailySessionAffinity) Unwrap() *OpenAIOAuthDailySessionAffinity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIOAuthDailySessionAffinity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIOAuthDailySessionAffinity) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIOAuthDailySessionAffinity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("logical_session_key=")
	builder.WriteString(_m.LogicalSessionKey)
	builder.WriteString(", ")
	builder.WriteString("business_date=")
	builder.WriteString(_m.BusinessDate)
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(_m.Generation)
	builder.WriteString(", ")
	builder.WriteString("slot_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.SlotIndex))
	builder.WriteString(", ")
	builder.WriteString("stream_session_id=")
	builder.WriteString(_m.StreamSessionID)
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIOAuthDailySessionAffinities is a parsable slice of OpenAIOAuthDailySessionAffinity.
type OpenAIOAuthDailySessionAffinities []*OpenAIOAuthDailySessionAffinity
