// Code generated by ent, DO NOT EDIT.

package openaioauthdailysessionpool

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaioauthdailysessionpool type in the database.
	Label = "open_aio_auth_daily_session_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldBusinessDate holds the string denoting the business_date field in the database.
	FieldBusinessDate = "business_date"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldStreamSession0 holds the string denoting the stream_session_0 field in the database.
	FieldStreamSession0 = "stream_session_0"
	// FieldStreamSession1 holds the string denoting the stream_session_1 field in the database.
	FieldStreamSession1 = "stream_session_1"
	// FieldStreamSession2 holds the string denoting the stream_session_2 field in the database.
	FieldStreamSession2 = "stream_session_2"
	// FieldSyncSession holds the string denoting the sync_session field in the database.
	FieldSyncSession = "sync_session"
	// FieldActiveStreams holds the string denoting the active_streams field in the database.
	FieldActiveStreams = "active_streams"
	// Table holds the table name of the openaioauthdailysessionpool in the database.
	Table = "openai_oauth_daily_session_pools"
)

// Columns holds all SQL columns for openaioauthdailysessionpool fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldBusinessDate,
	FieldGeneration,
	FieldStreamSession0,
	FieldStreamSession1,
	FieldStreamSession2,
	FieldSyncSession,
	FieldActiveStreams,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// BusinessDateValidator is a validator for the "business_date" field. It is called by the builders before save.
	BusinessDateValidator func(string) error
	// GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	GenerationValidator func(string) error
	// StreamSession0Validator is a validator for the "stream_session_0" field. It is called by the builders before save.
	StreamSession0Validator func(string) error
	// StreamSession1Validator is a validator for the "stream_session_1" field. It is called by the builders before save.
	StreamSession1Validator func(string) error
	// StreamSession2Validator is a validator for the "stream_session_2" field. It is called by the builders before save.
	StreamSession2Validator func(string) error
	// SyncSessionValidator is a validator for the "sync_session" field. It is called by the builders before save.
	SyncSessionValidator func(string) error
	// DefaultActiveStreams holds the default value on creation for the "active_streams" field.
	DefaultActiveStreams int
)

// OrderOption defines the ordering options for the OpenAIOAuthDailySessionPool queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByBusinessDate orders the results by the business_date field.
func ByBusinessDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessDate, opts...).ToFunc()
}

// ByGeneration orders the results by the generation field.
func ByGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneration, opts...).ToFunc()
}

// ByStreamSession0 orders the results by the stream_session_0 field.
func ByStreamSession0(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamSession0, opts...).ToFunc()
}

// ByStreamSession1 orders the results by the stream_session_1 field.
func ByStreamSession1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamSession1, opts...).ToFunc()
}

// ByStreamSession2 orders the results by the stream_session_2 field.
func ByStreamSession2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamSession2, opts...).ToFunc()
}

// BySyncSession orders the results by the sync_session field.
func BySyncSession(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncSession, opts...).ToFunc()
}

// ByActiveStreams orders the results by the active_streams field.
func ByActiveStreams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveStreams, opts...).ToFunc()
}
