// Code generated by ent, DO NOT EDIT.

package openaioauthdailysessionpool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldAccountID, v))
}

// BusinessDate applies equality check predicate on the "business_date" field. It's identical to BusinessDateEQ.
func BusinessDate(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldBusinessDate, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldGeneration, v))
}

// StreamSession0 applies equality check predicate on the "stream_session_0" field. It's identical to StreamSession0EQ.
func StreamSession0(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession0, v))
}

// StreamSession1 applies equality check predicate on the "stream_session_1" field. It's identical to StreamSession1EQ.
func StreamSession1(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession1, v))
}

// StreamSession2 applies equality check predicate on the "stream_session_2" field. It's identical to StreamSession2EQ.
func StreamSession2(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession2, v))
}

// SyncSession applies equality check predicate on the "sync_session" field. It's identical to SyncSessionEQ.
func SyncSession(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldSyncSession, v))
}

// ActiveStreams applies equality check predicate on the "active_streams" field. It's identical to ActiveStreamsEQ.
func ActiveStreams(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldActiveStreams, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldAccountID, v))
}

// BusinessDateEQ applies the EQ predicate on the "business_date" field.
func BusinessDateEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldBusinessDate, v))
}

// BusinessDateNEQ applies the NEQ predicate on the "business_date" field.
func BusinessDateNEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldBusinessDate, v))
}

// BusinessDateIn applies the In predicate on the "business_date" field.
func BusinessDateIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldBusinessDate, vs...))
}

// BusinessDateNotIn applies the NotIn predicate on the "business_date" field.
func BusinessDateNotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldBusinessDate, vs...))
}

// BusinessDateGT applies the GT predicate on the "business_date" field.
func BusinessDateGT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldBusinessDate, v))
}

// BusinessDateGTE applies the GTE predicate on the "business_date" field.
func BusinessDateGTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldBusinessDate, v))
}

// BusinessDateLT applies the LT predicate on the "business_date" field.
func BusinessDateLT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldBusinessDate, v))
}

// BusinessDateLTE applies the LTE predicate on the "business_date" field.
func BusinessDateLTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldBusinessDate, v))
}

// BusinessDateContains applies the Contains predicate on the "business_date" field.
func BusinessDateContains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldBusinessDate, v))
}

// BusinessDateHasPrefix applies the HasPrefix predicate on the "business_date" field.
func BusinessDateHasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldBusinessDate, v))
}

// BusinessDateHasSuffix applies the HasSuffix predicate on the "business_date" field.
func BusinessDateHasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldBusinessDate, v))
}

// BusinessDateEqualFold applies the EqualFold predicate on the "business_date" field.
func BusinessDateEqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldBusinessDate, v))
}

// BusinessDateContainsFold applies the ContainsFold predicate on the "business_date" field.
func BusinessDateContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldBusinessDate, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldGeneration, v))
}

// GenerationContains applies the Contains predicate on the "generation" field.
func GenerationContains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldGeneration, v))
}

// GenerationHasPrefix applies the HasPrefix predicate on the "generation" field.
func GenerationHasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldGeneration, v))
}

// GenerationHasSuffix applies the HasSuffix predicate on the "generation" field.
func GenerationHasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldGeneration, v))
}

// GenerationEqualFold applies the EqualFold predicate on the "generation" field.
func GenerationEqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldGeneration, v))
}

// GenerationContainsFold applies the ContainsFold predicate on the "generation" field.
func GenerationContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldGeneration, v))
}

// StreamSession0EQ applies the EQ predicate on the "stream_session_0" field.
func StreamSession0EQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession0, v))
}

// StreamSession0NEQ applies the NEQ predicate on the "stream_session_0" field.
func StreamSession0NEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldStreamSession0, v))
}

// StreamSession0In applies the In predicate on the "stream_session_0" field.
func StreamSession0In(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldStreamSession0, vs...))
}

// StreamSession0NotIn applies the NotIn predicate on the "stream_session_0" field.
func StreamSession0NotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldStreamSession0, vs...))
}

// StreamSession0GT applies the GT predicate on the "stream_session_0" field.
func StreamSession0GT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldStreamSession0, v))
}

// StreamSession0GTE applies the GTE predicate on the "stream_session_0" field.
func StreamSession0GTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldStreamSession0, v))
}

// StreamSession0LT applies the LT predicate on the "stream_session_0" field.
func StreamSession0LT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldStreamSession0, v))
}

// StreamSession0LTE applies the LTE predicate on the "stream_session_0" field.
func StreamSession0LTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldStreamSession0, v))
}

// StreamSession0Contains applies the Contains predicate on the "stream_session_0" field.
func StreamSession0Contains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldStreamSession0, v))
}

// StreamSession0HasPrefix applies the HasPrefix predicate on the "stream_session_0" field.
func StreamSession0HasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldStreamSession0, v))
}

// StreamSession0HasSuffix applies the HasSuffix predicate on the "stream_session_0" field.
func StreamSession0HasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldStreamSession0, v))
}

// StreamSession0EqualFold applies the EqualFold predicate on the "stream_session_0" field.
func StreamSession0EqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldStreamSession0, v))
}

// StreamSession0ContainsFold applies the ContainsFold predicate on the "stream_session_0" field.
func StreamSession0ContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldStreamSession0, v))
}

// StreamSession1EQ applies the EQ predicate on the "stream_session_1" field.
func StreamSession1EQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession1, v))
}

// StreamSession1NEQ applies the NEQ predicate on the "stream_session_1" field.
func StreamSession1NEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldStreamSession1, v))
}

// StreamSession1In applies the In predicate on the "stream_session_1" field.
func StreamSession1In(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldStreamSession1, vs...))
}

// StreamSession1NotIn applies the NotIn predicate on the "stream_session_1" field.
func StreamSession1NotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldStreamSession1, vs...))
}

// StreamSession1GT applies the GT predicate on the "stream_session_1" field.
func StreamSession1GT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldStreamSession1, v))
}

// StreamSession1GTE applies the GTE predicate on the "stream_session_1" field.
func StreamSession1GTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldStreamSession1, v))
}

// StreamSession1LT applies the LT predicate on the "stream_session_1" field.
func StreamSession1LT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldStreamSession1, v))
}

// StreamSession1LTE applies the LTE predicate on the "stream_session_1" field.
func StreamSession1LTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldStreamSession1, v))
}

// StreamSession1Contains applies the Contains predicate on the "stream_session_1" field.
func StreamSession1Contains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldStreamSession1, v))
}

// StreamSession1HasPrefix applies the HasPrefix predicate on the "stream_session_1" field.
func StreamSession1HasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldStreamSession1, v))
}

// StreamSession1HasSuffix applies the HasSuffix predicate on the "stream_session_1" field.
func StreamSession1HasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldStreamSession1, v))
}

// StreamSession1EqualFold applies the EqualFold predicate on the "stream_session_1" field.
func StreamSession1EqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldStreamSession1, v))
}

// StreamSession1ContainsFold applies the ContainsFold predicate on the "stream_session_1" field.
func StreamSession1ContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldStreamSession1, v))
}

// StreamSession2EQ applies the EQ predicate on the "stream_session_2" field.
func StreamSession2EQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldStreamSession2, v))
}

// StreamSession2NEQ applies the NEQ predicate on the "stream_session_2" field.
func StreamSession2NEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldStreamSession2, v))
}

// StreamSession2In applies the In predicate on the "stream_session_2" field.
func StreamSession2In(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldStreamSession2, vs...))
}

// StreamSession2NotIn applies the NotIn predicate on the "stream_session_2" field.
func StreamSession2NotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldStreamSession2, vs...))
}

// StreamSession2GT applies the GT predicate on the "stream_session_2" field.
func StreamSession2GT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldStreamSession2, v))
}

// StreamSession2GTE applies the GTE predicate on the "stream_session_2" field.
func StreamSession2GTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldStreamSession2, v))
}

// StreamSession2LT applies the LT predicate on the "stream_session_2" field.
func StreamSession2LT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldStreamSession2, v))
}

// StreamSession2LTE applies the LTE predicate on the "stream_session_2" field.
func StreamSession2LTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldStreamSession2, v))
}

// StreamSession2Contains applies the Contains predicate on the "stream_session_2" field.
func StreamSession2Contains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldStreamSession2, v))
}

// StreamSession2HasPrefix applies the HasPrefix predicate on the "stream_session_2" field.
func StreamSession2HasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldStreamSession2, v))
}

// StreamSession2HasSuffix applies the HasSuffix predicate on the "stream_session_2" field.
func StreamSession2HasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldStreamSession2, v))
}

// StreamSession2EqualFold applies the EqualFold predicate on the "stream_session_2" field.
func StreamSession2EqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldStreamSession2, v))
}

// StreamSession2ContainsFold applies the ContainsFold predicate on the "stream_session_2" field.
func StreamSession2ContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldStreamSession2, v))
}

// SyncSessionEQ applies the EQ predicate on the "sync_session" field.
func SyncSessionEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldSyncSession, v))
}

// SyncSessionNEQ applies the NEQ predicate on the "sync_session" field.
func SyncSessionNEQ(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldSyncSession, v))
}

// SyncSessionIn applies the In predicate on the "sync_session" field.
func SyncSessionIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldSyncSession, vs...))
}

// SyncSessionNotIn applies the NotIn predicate on the "sync_session" field.
func SyncSessionNotIn(vs ...string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldSyncSession, vs...))
}

// SyncSessionGT applies the GT predicate on the "sync_session" field.
func SyncSessionGT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldSyncSession, v))
}

// SyncSessionGTE applies the GTE predicate on the "sync_session" field.
func SyncSessionGTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldSyncSession, v))
}

// SyncSessionLT applies the LT predicate on the "sync_session" field.
func SyncSessionLT(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldSyncSession, v))
}

// SyncSessionLTE applies the LTE predicate on the "sync_session" field.
func SyncSessionLTE(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldSyncSession, v))
}

// SyncSessionContains applies the Contains predicate on the "sync_session" field.
func SyncSessionContains(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContains(FieldSyncSession, v))
}

// SyncSessionHasPrefix applies the HasPrefix predicate on the "sync_session" field.
func SyncSessionHasPrefix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasPrefix(FieldSyncSession, v))
}

// SyncSessionHasSuffix applies the HasSuffix predicate on the "sync_session" field.
func SyncSessionHasSuffix(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldHasSuffix(FieldSyncSession, v))
}

// SyncSessionEqualFold applies the EqualFold predicate on the "sync_session" field.
func SyncSessionEqualFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEqualFold(FieldSyncSession, v))
}

// SyncSessionContainsFold applies the ContainsFold predicate on the "sync_session" field.
func SyncSessionContainsFold(v string) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldContainsFold(FieldSyncSession, v))
}

// ActiveStreamsEQ applies the EQ predicate on the "active_streams" field.
func ActiveStreamsEQ(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldEQ(FieldActiveStreams, v))
}

// ActiveStreamsNEQ applies the NEQ predicate on the "active_streams" field.
func ActiveStreamsNEQ(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNEQ(FieldActiveStreams, v))
}

// ActiveStreamsIn applies the In predicate on the "active_streams" field.
func ActiveStreamsIn(vs ...int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldIn(FieldActiveStreams, vs...))
}

// ActiveStreamsNotIn applies the NotIn predicate on the "active_streams" field.
func ActiveStreamsNotIn(vs ...int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldNotIn(FieldActiveStreams, vs...))
}

// ActiveStreamsGT applies the GT predicate on the "active_streams" field.
func ActiveStreamsGT(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGT(FieldActiveStreams, v))
}

// ActiveStreamsGTE applies the GTE predicate on the "active_streams" field.
func ActiveStreamsGTE(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldGTE(FieldActiveStreams, v))
}

// ActiveStreamsLT applies the LT predicate on the "active_streams" field.
func ActiveStreamsLT(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLT(FieldActiveStreams, v))
}

// ActiveStreamsLTE applies the LTE predicate on the "active_streams" field.
func ActiveStreamsLTE(v int) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.FieldLTE(FieldActiveStreams, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIOAuthDailySessionPool) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIOAuthDailySessionPool) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIOAuthDailySessionPool) predicate.OpenAIOAuthDailySessionPool {
	return predicate.OpenAIOAuthDailySessionPool(sql.NotPredicates(p))
}
