// Code generated by ent, DO NOT EDIT.

package openaioauthdailysessionaffinity

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaioauthdailysessionaffinity type in the database.
	Label = "open_aio_auth_daily_session_affinity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldLogicalSessionKey holds the string denoting the logical_session_key field in the database.
	FieldLogicalSessionKey = "logical_session_key"
	// FieldBusinessDate holds the string denoting the business_date field in the database.
	FieldBusinessDate = "business_date"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldSlotIndex holds the string denoting the slot_index field in the database.
	FieldSlotIndex = "slot_index"
	// FieldStreamSessionID holds the string denoting the stream_session_id field in the database.
	FieldStreamSessionID = "stream_session_id"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// Table holds the table name of the openaioauthdailysessionaffinity in the database.
	Table = "openai_oauth_daily_session_affinities"
)

// Columns holds all SQL columns for openaioauthdailysessionaffinity fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldAPIKeyID,
	FieldLogicalSessionKey,
	FieldBusinessDate,
	FieldGeneration,
	FieldSlotIndex,
	FieldStreamSessionID,
	FieldLastSeenAt,
	FieldActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAPIKeyID holds the default value on creation for the "api_key_id" field.
	DefaultAPIKeyID int64
	// LogicalSessionKeyValidator is a validator for the "logical_session_key" field. It is called by the builders before save.
	LogicalSessionKeyValidator func(string) error
	// BusinessDateValidator is a validator for the "business_date" field. It is called by the builders before save.
	BusinessDateValidator func(string) error
	// GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	GenerationValidator func(string) error
	// StreamSessionIDValidator is a validator for the "stream_session_id" field. It is called by the builders before save.
	StreamSessionIDValidator func(string) error
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
	// UpdateDefaultLastSeenAt holds the default value on update for the "last_seen_at" field.
	UpdateDefaultLastSeenAt func() time.Time
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// OrderOption defines the ordering options for the OpenAIOAuthDailySessionAffinity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByLogicalSessionKey orders the results by the logical_session_key field.
func ByLogicalSessionKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogicalSessionKey, opts...).ToFunc()
}

// ByBusinessDate orders the results by the business_date field.
func ByBusinessDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessDate, opts...).ToFunc()
}

// ByGeneration orders the results by the generation field.
func ByGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneration, opts...).ToFunc()
}

// BySlotIndex orders the results by the slot_index field.
func BySlotIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlotIndex, opts...).ToFunc()
}

// ByStreamSessionID orders the results by the stream_session_id field.
func ByStreamSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamSessionID, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}
