// Code generated by ent, DO NOT EDIT.

package openaioauthdailysessionaffinity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldAccountID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldAPIKeyID, v))
}

// LogicalSessionKey applies equality check predicate on the "logical_session_key" field. It's identical to LogicalSessionKeyEQ.
func LogicalSessionKey(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldLogicalSessionKey, v))
}

// BusinessDate applies equality check predicate on the "business_date" field. It's identical to BusinessDateEQ.
func BusinessDate(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldBusinessDate, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldGeneration, v))
}

// SlotIndex applies equality check predicate on the "slot_index" field. It's identical to SlotIndexEQ.
func SlotIndex(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldSlotIndex, v))
}

// StreamSessionID applies equality check predicate on the "stream_session_id" field. It's identical to StreamSessionIDEQ.
func StreamSessionID(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldStreamSessionID, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldLastSeenAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldAccountID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldAPIKeyID, v))
}

// LogicalSessionKeyEQ applies the EQ predicate on the "logical_session_key" field.
func LogicalSessionKeyEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyNEQ applies the NEQ predicate on the "logical_session_key" field.
func LogicalSessionKeyNEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyIn applies the In predicate on the "logical_session_key" field.
func LogicalSessionKeyIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldLogicalSessionKey, vs...))
}

// LogicalSessionKeyNotIn applies the NotIn predicate on the "logical_session_key" field.
func LogicalSessionKeyNotIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldLogicalSessionKey, vs...))
}

// LogicalSessionKeyGT applies the GT predicate on the "logical_session_key" field.
func LogicalSessionKeyGT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyGTE applies the GTE predicate on the "logical_session_key" field.
func LogicalSessionKeyGTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyLT applies the LT predicate on the "logical_session_key" field.
func LogicalSessionKeyLT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyLTE applies the LTE predicate on the "logical_session_key" field.
func LogicalSessionKeyLTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyContains applies the Contains predicate on the "logical_session_key" field.
func LogicalSessionKeyContains(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContains(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyHasPrefix applies the HasPrefix predicate on the "logical_session_key" field.
func LogicalSessionKeyHasPrefix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasPrefix(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyHasSuffix applies the HasSuffix predicate on the "logical_session_key" field.
func LogicalSessionKeyHasSuffix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasSuffix(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyEqualFold applies the EqualFold predicate on the "logical_session_key" field.
func LogicalSessionKeyEqualFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEqualFold(FieldLogicalSessionKey, v))
}

// LogicalSessionKeyContainsFold applies the ContainsFold predicate on the "logical_session_key" field.
func LogicalSessionKeyContainsFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContainsFold(FieldLogicalSessionKey, v))
}

// BusinessDateEQ applies the EQ predicate on the "business_date" field.
func BusinessDateEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldBusinessDate, v))
}

// BusinessDateNEQ applies the NEQ predicate on the "business_date" field.
func BusinessDateNEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldBusinessDate, v))
}

// BusinessDateIn applies the In predicate on the "business_date" field.
func BusinessDateIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldBusinessDate, vs...))
}

// BusinessDateNotIn applies the NotIn predicate on the "business_date" field.
func BusinessDateNotIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldBusinessDate, vs...))
}

// BusinessDateGT applies the GT predicate on the "business_date" field.
func BusinessDateGT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldBusinessDate, v))
}

// BusinessDateGTE applies the GTE predicate on the "business_date" field.
func BusinessDateGTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldBusinessDate, v))
}

// BusinessDateLT applies the LT predicate on the "business_date" field.
func BusinessDateLT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldBusinessDate, v))
}

// BusinessDateLTE applies the LTE predicate on the "business_date" field.
func BusinessDateLTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldBusinessDate, v))
}

// BusinessDateContains applies the Contains predicate on the "business_date" field.
func BusinessDateContains(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContains(FieldBusinessDate, v))
}

// BusinessDateHasPrefix applies the HasPrefix predicate on the "business_date" field.
func BusinessDateHasPrefix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasPrefix(FieldBusinessDate, v))
}

// BusinessDateHasSuffix applies the HasSuffix predicate on the "business_date" field.
func BusinessDateHasSuffix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasSuffix(FieldBusinessDate, v))
}

// BusinessDateEqualFold applies the EqualFold predicate on the "business_date" field.
func BusinessDateEqualFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEqualFold(FieldBusinessDate, v))
}

// BusinessDateContainsFold applies the ContainsFold predicate on the "business_date" field.
func BusinessDateContainsFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContainsFold(FieldBusinessDate, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldGeneration, v))
}

// GenerationContains applies the Contains predicate on the "generation" field.
func GenerationContains(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContains(FieldGeneration, v))
}

// GenerationHasPrefix applies the HasPrefix predicate on the "generation" field.
func GenerationHasPrefix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasPrefix(FieldGeneration, v))
}

// GenerationHasSuffix applies the HasSuffix predicate on the "generation" field.
func GenerationHasSuffix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasSuffix(FieldGeneration, v))
}

// GenerationEqualFold applies the EqualFold predicate on the "generation" field.
func GenerationEqualFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEqualFold(FieldGeneration, v))
}

// GenerationContainsFold applies the ContainsFold predicate on the "generation" field.
func GenerationContainsFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContainsFold(FieldGeneration, v))
}

// SlotIndexEQ applies the EQ predicate on the "slot_index" field.
func SlotIndexEQ(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldSlotIndex, v))
}

// SlotIndexNEQ applies the NEQ predicate on the "slot_index" field.
func SlotIndexNEQ(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldSlotIndex, v))
}

// SlotIndexIn applies the In predicate on the "slot_index" field.
func SlotIndexIn(vs ...int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldSlotIndex, vs...))
}

// SlotIndexNotIn applies the NotIn predicate on the "slot_index" field.
func SlotIndexNotIn(vs ...int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldSlotIndex, vs...))
}

// SlotIndexGT applies the GT predicate on the "slot_index" field.
func SlotIndexGT(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldSlotIndex, v))
}

// SlotIndexGTE applies the GTE predicate on the "slot_index" field.
func SlotIndexGTE(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldSlotIndex, v))
}

// SlotIndexLT applies the LT predicate on the "slot_index" field.
func SlotIndexLT(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldSlotIndex, v))
}

// SlotIndexLTE applies the LTE predicate on the "slot_index" field.
func SlotIndexLTE(v int) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldSlotIndex, v))
}

// StreamSessionIDEQ applies the EQ predicate on the "stream_session_id" field.
func StreamSessionIDEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldStreamSessionID, v))
}

// StreamSessionIDNEQ applies the NEQ predicate on the "stream_session_id" field.
func StreamSessionIDNEQ(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldStreamSessionID, v))
}

// StreamSessionIDIn applies the In predicate on the "stream_session_id" field.
func StreamSessionIDIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldStreamSessionID, vs...))
}

// StreamSessionIDNotIn applies the NotIn predicate on the "stream_session_id" field.
func StreamSessionIDNotIn(vs ...string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldStreamSessionID, vs...))
}

// StreamSessionIDGT applies the GT predicate on the "stream_session_id" field.
func StreamSessionIDGT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldStreamSessionID, v))
}

// StreamSessionIDGTE applies the GTE predicate on the "stream_session_id" field.
func StreamSessionIDGTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldStreamSessionID, v))
}

// StreamSessionIDLT applies the LT predicate on the "stream_session_id" field.
func StreamSessionIDLT(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldStreamSessionID, v))
}

// StreamSessionIDLTE applies the LTE predicate on the "stream_session_id" field.
func StreamSessionIDLTE(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldStreamSessionID, v))
}

// StreamSessionIDContains applies the Contains predicate on the "stream_session_id" field.
func StreamSessionIDContains(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContains(FieldStreamSessionID, v))
}

// StreamSessionIDHasPrefix applies the HasPrefix predicate on the "stream_session_id" field.
func StreamSessionIDHasPrefix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasPrefix(FieldStreamSessionID, v))
}

// StreamSessionIDHasSuffix applies the HasSuffix predicate on the "stream_session_id" field.
func StreamSessionIDHasSuffix(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldHasSuffix(FieldStreamSessionID, v))
}

// StreamSessionIDEqualFold applies the EqualFold predicate on the "stream_session_id" field.
func StreamSessionIDEqualFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEqualFold(FieldStreamSessionID, v))
}

// StreamSessionIDContainsFold applies the ContainsFold predicate on the "stream_session_id" field.
func StreamSessionIDContainsFold(v string) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldContainsFold(FieldStreamSessionID, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldLTE(FieldLastSeenAt, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.FieldNEQ(FieldActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIOAuthDailySessionAffinity) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIOAuthDailySessionAffinity) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIOAuthDailySessionAffinity) predicate.OpenAIOAuthDailySessionAffinity {
	return predicate.OpenAIOAuthDailySessionAffinity(sql.NotPredicates(p))
}
